config/routes.rb
Rails.application.routes.draw do

  namespace :site do
    get '/', to: 'homepage#index'
    namespace :profile do
      resources :dashboard, only: [:index]
      resources :ads, except: [:show]
    end
  end

  namespace :backoffice do
    resources :send_mail, only: [:edit, :create]
    resources :categories, except: :show
    resources :admins, except: :show
  end

  devise_for :admins, skip: :registrations
  devise_for :members

  root to: 'site/homepage#index'
  get 'admin', to: 'backoffice/dashboard#index'

end

app/controllers/backoffice/admins_controller.rb
class Backoffice::AdminsController < ApplicationController
  before_action :authenticate_admin!
  before_action :get_admin, only: [:edit, :update, :destroy]
  before_action :set_admin, only: [:new, :create]

  layout 'backoffice'
  def index
    @admins = policy_scope(Admin).page(params[:page])
  end
  def new
    authorize @admin
  end
  def create
    @admin.update_attributes(permitted_attributes(@admin))
    if @admin.save
      flash[:success] = "Perfil '#{@admin.name}' adicionado à lista."
      redirect_to backoffice_admins_path
    else
      flash[:danger] = "Não foi possível adicionar '#{@admin.name}' à lista: #{@admin.errors.messages.flatten.join(' ')}."
      redirect_to new_backoffice_admin_path
    end
  end
  def edit
  end
  def update
    if password_blank?
      params[:admin].except!(:password, :password_confirmation)
    end
    if @admin.update(permitted_attributes(@admin))
      AdminMailer.update_email(current_admin, @admin).deliver_now
      flash[:success] = "Perfil '#{@admin.name}' alterado com sucesso."
      redirect_to backoffice_admins_path
    else
      flash[:danger] = "Não foi possível atualizar '#{@admin.name}': #{@admin.errors.messages.flatten.join(' ')}."
      redirect_to edit_backoffice_admin_path
    end
  end
  def destroy
    name = @admin.name
    authorize @admin
    if @admin.destroy
      flash[:success] = "Perfil '#{name}' excluído."
      redirect_to backoffice_admins_path
    else
      flash[:danger] = "Não foi possível excluir '#{@admin.email}'."
      redirect_to backoffice_admins_path
    end
  end
  private
  def get_admin
    @admin = Admin.find(params[:id])
  end
  def set_admin
    @admin = Admin.new
  end
  def pundit_user
    current_admin
  end
  def password_blank?
    params[:admin][:password].blank? && params[:admin][:password_confirmation].blank?
  end
end

app/controllers/backoffice/categories_controller.rb
class Backoffice::CategoriesController < ApplicationController
  before_action :authenticate_admin!
  before_action :get_category, only: [:edit, :update, :destroy]
  before_action :set_category, only: [:new, :create]

  layout 'backoffice'
  def index
    @categories = Category.order(:description).page params[:page]
  end
  def new
  end
  def create
    @category.update_attributes(category_params)
    if @category.save
      flash[:success] = "Categoria '#{@category.description}' adicionada à lista."
      redirect_to backoffice_categories_path
    else
      flash[:danger] = "Não foi possível adicionar categoria à lista: #{ @category.errors.messages[:description].join }"
      redirect_to new_backoffice_category_path
    end
  end
  def edit
  end
  def update
    if @category.update(category_params)
      flash[:success] = "Categoria '#{@category.description}' atualizada."
      redirect_to backoffice_categories_path
    else
      flash[:danger] = "Não foi possível atualizar '#{@category.description}'."
      redirect_to edit_backoffice_category_path
    end
  end
  def destroy
    description = @category.description
    if @category.destroy
      flash[:success] = "Categoria '#{description}' excluída."
      redirect_to backoffice_categories_path
    else
      flash[:danger] = "Não foi possível excluir '#{description}'."
      redirect_to backoffice_categories_path
    end
  end
  private
  def get_category
    @category = Category.find(params[:id])
  end
  def set_category
    @category = Category.new
  end
  def category_params
    params.require(:category).permit(:description)
  end
end

app/controllers/backoffice/dashboard_controller.rb
class Backoffice::DashboardController < ApplicationController
  before_action :authenticate_admin!

  layout 'backoffice'
  def index
    #code
  end
end

app/controllers/backoffice/send_mail_controller.rb
class Backoffice::SendMailController < ApplicationController
  def edit
    @admin = Admin.find(params[:id])
    respond_to do |format|
      format.js
    end
  end

  def create
    begin
      AdminMailer.send_email(current_admin, params[:recipient], params[:subject], params[:message]).deliver_now
      flash[:success] = 'Email enviado com sucesso.'
      redirect_to backoffice_admins_path
    rescue
      flash[:danger] = 'Erro ao enviar email. Tente novamente.'
      redirect_to backoffice_admins_path
    end
  end
end

app/helpers/backoffice/admins_helper.rb
module Backoffice::AdminsHelper
  OptionsForRoles = Struct.new(:id, :description)

  def options_for_roles
    Admin.roles_i18n.map do |key, val|
      OptionsForRoles.new(key,val)
    end
  end

end

app/helpers/backoffice/categories_helper.rb
module Backoffice::CategoriesHelper
end

app/helpers/backoffice/dashboard_helper.rb
module Backoffice::DashboardHelper
end

app/helpers/backoffice/send_mail_helper.rb
module Backoffice::SendMailHelper
end

app/views/backoffice/admins/_form.html.erb
<div class="row">
  <div class="col-lg-8">
    <div class="panel panel-success">
      <div class="panel-heading">
        <h3 class="panel-title"><%= header %></h3>
      </div>
      <%= form_for([:backoffice, @admin]) do |f| %>
        <div class="panel-body">
          <div class="row">
            <div class="col-sm-6">
              <div class="form-group">
                <%= f.label :name %>
                <%= f.text_field :name, class: "form-control" %>
              </div>
            </div>
            <div class="col-sm-6">
              <div class="form-group">
                <%= f.label :email %>
                <%= f.email_field :email, class: "form-control" %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-6">
              <div class="form-group">
                <%= f.label :password %>
                <%= f.password_field :password, class: "form-control" %>
                <p class="help-block">Mínimo 6 caracteres</p>
              </div>
            </div>
            <div class="col-sm-6">
              <div class="form-group">
                <%= f.label :password_confirmation %>
                <%= f.password_field :password_confirmation, class: "form-control" %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-12">
              <% if policy(@admin).edit? %>
              <div class="form-group">
                <label>Acesso</label><br>
                <%= f.collection_radio_buttons(:role, options_for_roles, :id, :description) do |b| %>
                  <%= b.label { b.radio_button } %>&nbsp;<%= b.text %><br>
                <% end %>
              </div>
              <% end %>
            </div>
          </div>
        </div>
        <div class="panel-footer">
          <%= f.submit class: "btn btn-success" %>
          <%= link_to fa_icon("arrow-left", text: "Voltar"), backoffice_admins_path, class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/backoffice/admins/_sendMail.html.erb
<div class="modal fade" id="sendEmailModal" tabindex="-1" role="dialog" aria-labelledby="sendEmailModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header bg-success">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="sendEmailModalLabel"></h4>
      </div>
      <div class="modal-body">
      <%= form_tag(backoffice_send_mail_index_path) do %>
        <div class="form-group">
          <label for="recipient" class="control-label">Para:</label>
          <%= text_field_tag(:recipient, nil, readonly: 'readonly', class:"form-control") %>
        </div>
        <div class="form-group">
          <label for="subject" class="control-label">Assunto:</label>
          <%= text_field_tag(:subject, nil, class:"form-control", required: 'required') %>
        </div>
        <div class="form-group">
          <label for="message" class="control-label">Mensagem:</label>
          <%= text_area_tag(:message, nil, class:"form-control", required: 'required') %>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
        <button type="submit" class="btn btn-primary">Enviar Mensagem</button>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/backoffice/admins/edit.html.erb
<%= render 'form', header: "Editar Administrador: #{@admin.name}" %>

app/views/backoffice/admins/index.html.erb
<div class="panel panel-success">
  <div class="panel-heading">
    <div class="row">
      <div class="col-lg-8">
        <p class="panel-title">
          <%= fa_icon("users") %>
          <%= page_entries_info(@admins) %>
        </p>
      </div>
      <% if policy(@admins).new? %>
      <div class="col-lg-4 text-right">
        <%= link_to fa_icon("plus-circle", text: "Novo Administrador"), new_backoffice_admin_path, class: "btn btn-success", style: "margin-top: 0;" %>
      </div>
      <% end %>
    </div>
  </div>
  <div class="panel-body">
    <div class="table-responsive">
      <table class="table table-striped table-hover table-condensed">
        <thead>
          <tr>
            <th><%= t(Admin.human_attribute_name(:name)) %></th>
            <th><%= t(Admin.human_attribute_name(:email)) %></th>
            <th><%= t(Admin.human_attribute_name(:role)) %></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @admins.each do |a| %>
          <% if a != current_admin %>
          <tr>
            <td><%= a.name %></td>
            <td><%= a.email %></td>
            <td><%= a.role_i18n %></td>
            <td>
              <%= link_to fa_icon("envelope"),
                '#',
                class: "btn btn-circle btn-primary",
                data: {
                  toggle: 'modal',
                  target: '#sendEmailModal',
                  name: a.name,
                  email: a.email
                }
              %>
              <%= link_to fa_icon("pencil"), edit_backoffice_admin_path(a), class: "btn btn-circle btn-warning" %>
              <% if policy(@admins).destroy? %>
                <%= link_to fa_icon("trash-o"),
                backoffice_admin_path(a),
                method: :delete,
                data: { confirm: "Deseja excluir #{a.name}?" },
                class: "btn btn-circle btn-danger" %>
              <% end %>
            </td>
          </tr>
          <% else %>
          <tr>
            <td><%= a.name %></td>
            <td><%= a.email %></td>
            <td><%= a.role_i18n %></td>
            <td></td>
          </tr>
          <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="panel-footer">
    <div class="row">
      <div class="col-lg-12 text-center">
        <%= paginate @admins %>
      </div>
    </div>
  </div>
</div>
<%= render "sendMail" %>

app/views/backoffice/admins/new.html.erb
<%= render 'form', header: "Novo Administrador" %>