config/routes.rb
Rails.application.routes.draw do

  namespace :site do
    get '/', to: 'homepage#index'
    namespace :profile do
      resources :dashboard, only: [:index]
      resources :ads, except: [:show]
    end
  end

  namespace :backoffice do
    resources :send_mail, only: [:edit, :create]
    resources :categories, except: :show
    resources :admins, except: :show
  end

  devise_for :admins, skip: :registrations
  devise_for :members

  root to: 'site/homepage#index'
  get 'admin', to: 'backoffice/dashboard#index'

end

app/controllers/site/homepage_controller.rb
class Site::HomepageController < SiteController
  def index
    @categories = Category.order_by_description
    @ads = Ad.all.limit(9)
  end
end

app/controllers/site/profile/ads_controller.rb
class Site::Profile::AdsController < Site::ProfileController
  before_action :set_ad, only: [:edit, :update, :destroy]
  before_action :get_ad, only: [:new, :create]
  def index
    @ads = current_member.ads.order(created_at: :desc)
  end
  def new
    #code
  end
  def create
    @ad.update_attributes(params_ad)
    @ad.member = current_member
    if @ad.save
      redirect_to site_profile_ads_path
      flash[:success] = "Anúncio criado com sucesso!"
    else
      render :new
    end
  end
  def edit

  end
  def update
    if @ad.update(params_ad)
      redirect_to site_profile_ads_path
      flash[:success] = "Anúncio atualizado com sucesso!"
    else
      render :edit
    end
  end
  def destroy
    if @ad.destroy
      redirect_to site_profile_ads_path
      flash[:success] = "Anúncio excluído com sucesso!"
    else
      render :index
      flash[:danger] = "Erro ao excluir o anúncio: #{@ad.errors.messages.flatten.join(' ')}"
    end
  end
  private
  def get_ad
    @ad = Ad.new
  end
  def set_ad
    @ad = Ad.find(params[:id])
  end
  def params_ad
    params.require(:ad).permit(:title, :description, :category_id, :price, :picture, :finish_date)
  end
end

app/controllers/site/profile/dashboard_controller.rb
class Site::Profile::DashboardController < Site::ProfileController
  def index
  end
end

app/controllers/site/profile_controller.rb
class Site::ProfileController < SiteController
  layout 'profile'
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  layout 'site'
end

app/helpers/site/homepage_helper.rb
module Site::HomepageHelper
end

app/helpers/site/profile/ads_helper.rb
module Site::Profile::AdsHelper
end

app/helpers/site/profile/dashboard_helper.rb
module Site::Profile::DashboardHelper
end

app/views/site/partials/_footer.html.erb
<!-- Footer -->
<footer class="py-5 bg-dark">
  <div class="container">
    <p class="m-0 text-center text-white">&copy; EscamboApp <%= Date.today.year %></p>
  </div>
  <!-- /.container -->
</footer>

app/views/site/partials/_navbar.html.erb
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container-fluid">
    <%= link_to fa_icon("shopping-cart", text: "EscamboApp"), root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <% if member_signed_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_member.name %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to fa_icon("user", text: "Conta"), site_profile_dashboard_index_path	, class: "dropdown-item" %>
            <%= link_to fa_icon("power-off", text: "Logoff"), destroy_member_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
        <% else %>
        <li class="nav-item">
          <%= link_to fa_icon("sign-in", text: "Login"), new_member_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to fa_icon("user-plus", text: "Criar Conta"), new_member_registration_path, class: "nav-link" %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/site/partials/_sidebar.html.erb
<div id="wrapper" class="toggled">

    <!-- Sidebar -->
    <div id="sidebar-wrapper">
        <ul class="sidebar-nav">
          <li>
            <%= link_to fa_icon("dashboard", text: "Painel"), site_profile_dashboard_index_path %>
          </li>
            <li>
                <%= link_to fa_icon("dollar", text: "Anúncios"), site_profile_ads_path %>
            </li>
        </ul>
    </div>
    <!-- /#sidebar-wrapper -->

    <!-- Page Content -->
    <div id="page-content-wrapper">
      <%= render "partials/flash" %>
      <%= yield %>
    </div>
    <!-- /#page-content-wrapper -->

</div>
<!-- /#wrapper -->