config/routes.rb
Rails.application.routes.draw do

  namespace :site do
    get '/', to: 'homepage#index'
    namespace :profile do
      resources :dashboard, only: [:index]
      resources :ads, except: [:show]
    end
  end

  namespace :backoffice do
    resources :send_mail, only: [:edit, :create]
    resources :categories, except: :show
    resources :admins, except: :show
  end

  devise_for :admins, skip: :registrations
  devise_for :members

  root to: 'site/homepage#index'
  get 'admin', to: 'backoffice/dashboard#index'

end

app/controllers/backoffice/admins_controller.rb
class Backoffice::AdminsController < ApplicationController
  before_action :authenticate_admin!
  before_action :get_admin, only: [:edit, :update, :destroy]
  before_action :set_admin, only: [:new, :create]

  layout 'backoffice'
  def index
    @admins = policy_scope(Admin).page(params[:page])
  end
  def new
    authorize @admin
  end
  def create
    @admin.update_attributes(permitted_attributes(@admin))
    if @admin.save
      flash[:success] = "Perfil '#{@admin.name}' adicionado à lista."
      redirect_to backoffice_admins_path
    else
      flash[:danger] = "Não foi possível adicionar '#{@admin.name}' à lista: #{@admin.errors.messages.flatten.join(' ')}."
      redirect_to new_backoffice_admin_path
    end
  end
  def edit
  end
  def update
    if password_blank?
      params[:admin].except!(:password, :password_confirmation)
    end
    if @admin.update(permitted_attributes(@admin))
      AdminMailer.update_email(current_admin, @admin).deliver_now
      flash[:success] = "Perfil '#{@admin.name}' alterado com sucesso."
      redirect_to backoffice_admins_path
    else
      flash[:danger] = "Não foi possível atualizar '#{@admin.name}': #{@admin.errors.messages.flatten.join(' ')}."
      redirect_to edit_backoffice_admin_path
    end
  end
  def destroy
    name = @admin.name
    authorize @admin
    if @admin.destroy
      flash[:success] = "Perfil '#{name}' excluído."
      redirect_to backoffice_admins_path
    else
      flash[:danger] = "Não foi possível excluir '#{@admin.email}'."
      redirect_to backoffice_admins_path
    end
  end
  private
  def get_admin
    @admin = Admin.find(params[:id])
  end
  def set_admin
    @admin = Admin.new
  end
  def pundit_user
    current_admin
  end
  def password_blank?
    params[:admin][:password].blank? && params[:admin][:password_confirmation].blank?
  end
end

app/controllers/backoffice/categories_controller.rb
class Backoffice::CategoriesController < ApplicationController
  before_action :authenticate_admin!
  before_action :get_category, only: [:edit, :update, :destroy]
  before_action :set_category, only: [:new, :create]

  layout 'backoffice'
  def index
    @categories = Category.order(:description).page params[:page]
  end
  def new
  end
  def create
    @category.update_attributes(category_params)
    if @category.save
      flash[:success] = "Categoria '#{@category.description}' adicionada à lista."
      redirect_to backoffice_categories_path
    else
      flash[:danger] = "Não foi possível adicionar categoria à lista: #{ @category.errors.messages[:description].join }"
      redirect_to new_backoffice_category_path
    end
  end
  def edit
  end
  def update
    if @category.update(category_params)
      flash[:success] = "Categoria '#{@category.description}' atualizada."
      redirect_to backoffice_categories_path
    else
      flash[:danger] = "Não foi possível atualizar '#{@category.description}'."
      redirect_to edit_backoffice_category_path
    end
  end
  def destroy
    description = @category.description
    if @category.destroy
      flash[:success] = "Categoria '#{description}' excluída."
      redirect_to backoffice_categories_path
    else
      flash[:danger] = "Não foi possível excluir '#{description}'."
      redirect_to backoffice_categories_path
    end
  end
  private
  def get_category
    @category = Category.find(params[:id])
  end
  def set_category
    @category = Category.new
  end
  def category_params
    params.require(:category).permit(:description)
  end
end

app/controllers/backoffice/dashboard_controller.rb
class Backoffice::DashboardController < ApplicationController
  before_action :authenticate_admin!

  layout 'backoffice'
  def index
    #code
  end
end

app/controllers/backoffice/send_mail_controller.rb
class Backoffice::SendMailController < ApplicationController
  def edit
    @admin = Admin.find(params[:id])
    respond_to do |format|
      format.js
    end
  end

  def create
    begin
      AdminMailer.send_email(current_admin, params[:recipient], params[:subject], params[:message]).deliver_now
      flash[:success] = 'Email enviado com sucesso.'
      redirect_to backoffice_admins_path
    rescue
      flash[:danger] = 'Erro ao enviar email. Tente novamente.'
      redirect_to backoffice_admins_path
    end
  end
end

app/helpers/backoffice/admins_helper.rb
module Backoffice::AdminsHelper
  OptionsForRoles = Struct.new(:id, :description)

  def options_for_roles
    Admin.roles_i18n.map do |key, val|
      OptionsForRoles.new(key,val)
    end
  end

end

app/helpers/backoffice/categories_helper.rb
module Backoffice::CategoriesHelper
end

app/helpers/backoffice/dashboard_helper.rb
module Backoffice::DashboardHelper
end

app/helpers/backoffice/send_mail_helper.rb
module Backoffice::SendMailHelper
end

app/views/backoffice/partials/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="<%= admin_path %>">EscamboApp - Administrativo</a>
  </div>
  <ul class="nav navbar-top-links navbar-right">
    <li class="dropdown">
      <a class="dropdown-toggle" data-toggle="dropdown" href="#">
        <%= fa_icon("gears", text: "#{current_admin.name}") %>
        <%= fa_icon("caret-down") %>
      </a>
      <ul class="dropdown-menu dropdown-settings">
        <li>
          <%= link_to fa_icon("edit", text: "Editar Perfil"), edit_backoffice_admin_path(current_admin) %>
        </li>
        <li>
          <%= link_to fa_icon("power-off", text: "Logoff"), destroy_admin_session_path, method: :delete %>
        </li>
      </ul>
    </li>
  </ul>
</nav>

app/views/backoffice/partials/_sidebar.html.erb
<div class="navbar-default sidebar" role="navigation">
  <div class="sidebar-nav navbar-collapse">
    <ul class="nav" id="side-menu">
      <li>
        <%= link_to fa_icon("dashboard", text: "Painel"), admin_path, class: "text-info" %>
      </li>
      <li>
        <%= link_to fa_icon("tags", text: "Categorias"), backoffice_categories_path %>
      </li>
      <li>
        <%= link_to fa_icon("users", text: "Administradores"), backoffice_admins_path, class: "text-success" %>
      </li>
    </ul>
  </div>
</div>